package trabalhofinal.view;

import trabalhofinal.persistence.ConexaoBD;

/**
 *
 * @author Douglas Soares
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conect = new ConexaoBD();
    TelaMedico telaMedico = new TelaMedico();
    TelaPaciente telaPaciente = new TelaPaciente();
    TelaAgendamento telaAgenda = new TelaAgendamento();
    TelaExames telaExames = new TelaExames();

    public TelaPrincipal() {
        initComponents();
        telaPaciente.setResizable(false);
        telaMedico.setResizable(false);
        telaAgenda.setResizable(false);
        telaExames.setResizable(false);
        conect.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadPac = new javax.swing.JButton();
        jButtonCadMed = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jLabelAgenda = new javax.swing.JLabel();
        jLabelCadPac = new javax.swing.JLabel();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jButtonExames = new javax.swing.JButton();
        jLabelExames = new javax.swing.JLabel();
        jLabelTxtFrameBemVindo = new javax.swing.JLabel();
        jLabelTxtUsuario = new javax.swing.JLabel();
        jLabelSetUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadPac = new javax.swing.JMenuItem();
        jMenuItemCadMed = new javax.swing.JMenuItem();
        jMenuItemCadUsu = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jMenuItemAgendado = new javax.swing.JMenuItem();
        jMenuItemEspera = new javax.swing.JMenuItem();
        jMenuItemExecutado = new javax.swing.JMenuItem();
        jMenuExame = new javax.swing.JMenu();
        jMenuItemAgendar = new javax.swing.JMenuItem();
        jMenuItemCancelar = new javax.swing.JMenuItem();
        jMenuItemRealizar = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemFerramentaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrameBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrameBemVindo.setTitle("Bem vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInternal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInternal.setLayout(null);

        jButtonCadPac.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhofinal/imagens/paciente2D.png"))); // NOI18N
        jButtonCadPac.setToolTipText("Cadastro de Paciente");
        jButtonCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadPac);
        jButtonCadPac.setBounds(100, 50, 80, 73);

        jButtonCadMed.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhofinal/imagens/medico.png"))); // NOI18N
        jButtonCadMed.setToolTipText("Cadastro de Médico");
        jButtonCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadMed);
        jButtonCadMed.setBounds(260, 50, 80, 70);

        jButtonAgenda.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhofinal/imagens/agenda.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Consulta Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(420, 50, 80, 70);

        jLabelAgenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAgenda.setText("Agenda");
        jPanelInternal.add(jLabelAgenda);
        jLabelAgenda.setBounds(440, 130, 52, 32);

        jLabelCadPac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadPac.setText("Paciente");
        jPanelInternal.add(jLabelCadPac);
        jLabelCadPac.setBounds(110, 130, 47, 29);

        jLabelFundoBemVindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFundoBemVindo.setText("Médico");
        jPanelInternal.add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(280, 130, 81, 29);

        jButtonFecharBemVindo.setText("Fechar");
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(850, 370, 73, 23);

        jButtonExames.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhofinal/imagens/exames.png"))); // NOI18N
        jButtonExames.setToolTipText("Exames");
        jButtonExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExamesActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonExames);
        jButtonExames.setBounds(560, 50, 80, 70);

        jLabelExames.setText("Exames");
        jPanelInternal.add(jLabelExames);
        jLabelExames.setBounds(580, 130, 50, 20);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(10, 70, 930, 410);

        jLabelTxtFrameBemVindo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTxtFrameBemVindo.setText("SISTEMA PARA GERENCIAMENTO");
        jInternalFrameBemVindo.getContentPane().add(jLabelTxtFrameBemVindo);
        jLabelTxtFrameBemVindo.setBounds(350, 0, 470, 80);

        jLabelTxtUsuario.setText("Usuario: ");
        jInternalFrameBemVindo.getContentPane().add(jLabelTxtUsuario);
        jLabelTxtUsuario.setBounds(20, 480, 60, 30);

        jLabelSetUsuario.setText("jLabel2");
        jInternalFrameBemVindo.getContentPane().add(jLabelSetUsuario);
        jLabelSetUsuario.setBounds(70, 480, 220, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(30, 20, 960, 540);

        jMenuCadastro.setText("Cadastros");

        jMenuItemCadPac.setText("Pacientes");
        jMenuItemCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadPac);

        jMenuItemCadMed.setText("Médicos");
        jMenuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMed);

        jMenuItemCadUsu.setText("Usuários");
        jMenuCadastro.add(jMenuItemCadUsu);

        jMenuBar1.add(jMenuCadastro);

        jMenuAgenda.setText("Agenda");

        jMenuItemAgendado.setText("Exames Agendados");
        jMenuAgenda.add(jMenuItemAgendado);

        jMenuItemEspera.setText("Lista de Espera");
        jMenuAgenda.add(jMenuItemEspera);

        jMenuItemExecutado.setText("Exames Executados");
        jMenuAgenda.add(jMenuItemExecutado);

        jMenuBar1.add(jMenuAgenda);

        jMenuExame.setText("Exames");

        jMenuItemAgendar.setText("Agendar Exame");
        jMenuItemAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendarActionPerformed(evt);
            }
        });
        jMenuExame.add(jMenuItemAgendar);

        jMenuItemCancelar.setText("Cancelar Exame");
        jMenuExame.add(jMenuItemCancelar);

        jMenuItemRealizar.setText("Realizar Exame");
        jMenuExame.add(jMenuItemRealizar);

        jMenuBar1.add(jMenuExame);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemFerramentaBemVindo.setText("Bem Vindo");
        jMenuItemFerramentaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFerramentaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemFerramentaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1037, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacActionPerformed
        telaPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPacActionPerformed

    private void jMenuItemAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgendarActionPerformed

    private void jButtonCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacActionPerformed
        telaPaciente.setVisible(true);
    }//GEN-LAST:event_jButtonCadPacActionPerformed

    private void jButtonCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedActionPerformed
        telaMedico.setVisible(true);
    }//GEN-LAST:event_jButtonCadMedActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        telaAgenda.setVisible(true);
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemFerramentaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFerramentaBemVindoActionPerformed
        TelaPrincipal telaP = new TelaPrincipal();
        telaP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemFerramentaBemVindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conect.desconectar();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExamesActionPerformed
        TelaExames telaE = new TelaExames();
        telaE.setVisible(true);
    }//GEN-LAST:event_jButtonExamesActionPerformed

    private void jMenuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedActionPerformed
        TelaMedico telaM = new TelaMedico();
        telaM.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadMed;
    private javax.swing.JButton jButtonCadPac;
    private javax.swing.JButton jButtonExames;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCadPac;
    private javax.swing.JLabel jLabelExames;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JLabel jLabelSetUsuario;
    private javax.swing.JLabel jLabelTxtFrameBemVindo;
    private javax.swing.JLabel jLabelTxtUsuario;
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuExame;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemAgendado;
    private javax.swing.JMenuItem jMenuItemAgendar;
    private javax.swing.JMenuItem jMenuItemCadMed;
    private javax.swing.JMenuItem jMenuItemCadPac;
    private javax.swing.JMenuItem jMenuItemCadUsu;
    private javax.swing.JMenuItem jMenuItemCancelar;
    private javax.swing.JMenuItem jMenuItemEspera;
    private javax.swing.JMenuItem jMenuItemExecutado;
    private javax.swing.JMenuItem jMenuItemFerramentaBemVindo;
    private javax.swing.JMenuItem jMenuItemRealizar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
