package trabalhofinal.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import trabalhofinal.model.ModelMed;
import trabalhofinal.model.ModelTabela;
import trabalhofinal.persistence.ConexaoBD;
import trabalhofinal.persistence.MedicoDAO;

/**
 *
 * @author 320079589
 */
public class TelaMedico extends javax.swing.JFrame {

    ModelMed medico = new ModelMed();
    MedicoDAO persistMed = new MedicoDAO();
    String event = "";
    ConexaoBD conn = new ConexaoBD();

    public TelaMedico() {
        initComponents();
        preencherTabela("select * from medico order by cd_medico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeMed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDtnMed = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCpfMed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexoMed = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCrmMed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelMed = new javax.swing.JTextField();
        jButtonNovoCadMed = new javax.swing.JButton();
        jButtonEditMed = new javax.swing.JButton();
        jButtonDelMed = new javax.swing.JButton();
        jButtonSalvarMed = new javax.swing.JButton();
        jButtonSairMed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jButtonPesqMed = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPesqMed = new javax.swing.JTextField();
        jButtonCancelMed = new javax.swing.JButton();
        jTextFieldCodMed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNomeMed.setEnabled(false);
        jTextFieldNomeMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeMedActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome: ");

        jLabel2.setText("Data Nasc.:");

        jFormattedTextFieldDtnMed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldDtnMed.setEnabled(false);

        jLabel3.setText("CPF:");

        jTextFieldCpfMed.setEnabled(false);
        jTextFieldCpfMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfMedActionPerformed(evt);
            }
        });

        jLabel4.setText("Sexo:");

        jComboBoxSexoMed.setMaximumRowCount(2);
        jComboBoxSexoMed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Masculino", "Feminino" }));
        jComboBoxSexoMed.setEnabled(false);
        jComboBoxSexoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoMedActionPerformed(evt);
            }
        });

        jLabel5.setText("CRM:");

        jTextFieldCrmMed.setEnabled(false);

        jLabel6.setText("Telefone:");

        jTextFieldTelMed.setEnabled(false);
        jTextFieldTelMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelMedActionPerformed(evt);
            }
        });

        jButtonNovoCadMed.setText("Novo");
        jButtonNovoCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadMedActionPerformed(evt);
            }
        });

        jButtonEditMed.setText("Editar");
        jButtonEditMed.setEnabled(false);
        jButtonEditMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMedActionPerformed(evt);
            }
        });

        jButtonDelMed.setText("Deletar");
        jButtonDelMed.setEnabled(false);
        jButtonDelMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelMedActionPerformed(evt);
            }
        });

        jButtonSalvarMed.setText("Salvar");
        jButtonSalvarMed.setEnabled(false);
        jButtonSalvarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarMedActionPerformed(evt);
            }
        });

        jButtonSairMed.setText("Sair");
        jButtonSairMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairMedActionPerformed(evt);
            }
        });

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jButtonPesqMed.setText("Pesquisar");
        jButtonPesqMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqMedActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CADASTRO DE MÉDICO");

        jTextFieldPesqMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesqMedActionPerformed(evt);
            }
        });

        jButtonCancelMed.setText("Cancelar");
        jButtonCancelMed.setEnabled(false);
        jButtonCancelMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelMedActionPerformed(evt);
            }
        });

        jTextFieldCodMed.setEnabled(false);

        jLabel8.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodMed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNovoCadMed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPesqMed, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSalvarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonEditMed, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonDelMed, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCancelMed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonSairMed, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jButtonPesqMed)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCrmMed, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextFieldCpfMed))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldDtnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxSexoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodMed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSexoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTelMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCrmMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldDtnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jTextFieldPesqMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesqMed)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSairMed)
                    .addComponent(jButtonCancelMed)
                    .addComponent(jButtonDelMed)
                    .addComponent(jButtonEditMed)
                    .addComponent(jButtonSalvarMed)
                    .addComponent(jButtonNovoCadMed))
                .addGap(14, 14, 14))
        );

        setSize(new java.awt.Dimension(766, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCpfMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfMedActionPerformed

    }//GEN-LAST:event_jTextFieldCpfMedActionPerformed

    private void jComboBoxSexoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoMedActionPerformed

    private void jButtonSairMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairMedActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairMedActionPerformed

    private void jTextFieldPesqMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesqMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesqMedActionPerformed

    private void jButtonNovoCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadMedActionPerformed
        event = "NOVO";
        jButtonNovoCadMed.setEnabled(false);
        jButtonSalvarMed.setEnabled(true);
        jTextFieldNomeMed.setEnabled(true);
        jTextFieldCrmMed.setEnabled(true);
        jTextFieldTelMed.setEnabled(true);
        jComboBoxSexoMed.setEnabled(true);
        jFormattedTextFieldDtnMed.setEnabled(true);
        jTextFieldCpfMed.setEnabled(true);
        jButtonPesqMed.setEnabled(false);
        jTextFieldPesqMed.setEnabled(false);
        jButtonCancelMed.setEnabled(true);
        jButtonNovoCadMed.setEnabled(true);


    }//GEN-LAST:event_jButtonNovoCadMedActionPerformed

    private void jButtonSalvarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarMedActionPerformed
        if (jTextFieldNomeMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o NOME para continuar!");
            jTextFieldNomeMed.requestFocus();
        } else if (jTextFieldCpfMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha CPF para continuar!");
            jTextFieldCpfMed.requestFocus();
        } else if (jTextFieldCrmMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o CRM para continuar!");
            jTextFieldCrmMed.requestFocus();
        } else if (jComboBoxSexoMed.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha o SEXO para continuar!");
            jComboBoxSexoMed.requestFocus();
        } else if (jTextFieldTelMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o Telefone para continuar!");
            jTextFieldTelMed.requestFocus();
        } else if (jFormattedTextFieldDtnMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha a Data de Nasc. para continuar!");
            jFormattedTextFieldDtnMed.requestFocus();
        } else {
            if ("NOVO".equals(event)) {
                medico.setNome(jTextFieldNomeMed.getText());
                medico.setCpf(jTextFieldCpfMed.getText());
                medico.setCrm(Integer.parseInt(jTextFieldCrmMed.getText()));
                medico.setSexo((String) jComboBoxSexoMed.getSelectedItem());
                medico.setTelefone(jTextFieldTelMed.getText());
                medico.setDtn(jFormattedTextFieldDtnMed.getText());
                persistMed.salvar(medico);
                jTextFieldNomeMed.setText("");
                jTextFieldCpfMed.setText("");
                jTextFieldCrmMed.setText("");
                jFormattedTextFieldDtnMed.setText("");
                jTextFieldTelMed.setText("");
                jComboBoxSexoMed.setSelectedItem("");
                jTextFieldNomeMed.setEnabled(false);
                jTextFieldCpfMed.setEnabled(false);
                jTextFieldCrmMed.setEnabled(false);
                jTextFieldTelMed.setEnabled(false);
                jFormattedTextFieldDtnMed.setEnabled(false);
                jComboBoxSexoMed.setEnabled(false);
                jButtonSalvarMed.setEnabled(false);
                jButtonPesqMed.setEnabled(true);
                jTextFieldPesqMed.setEnabled(true);
                preencherTabela("select * from medico order by cd_medico");

            } else {
                medico.setCod(Integer.parseInt(jTextFieldCodMed.getText()));
                medico.setNome(jTextFieldNomeMed.getText());
                medico.setCpf(jTextFieldCpfMed.getText());
                medico.setCrm(Integer.parseInt(jTextFieldCrmMed.getText()));
                medico.setSexo((String) jComboBoxSexoMed.getSelectedItem());
                medico.setTelefone(jTextFieldTelMed.getText());
                medico.setDtn(jFormattedTextFieldDtnMed.getText());
                persistMed.editar(medico);
                jTextFieldNomeMed.setEnabled(false);
                jTextFieldCpfMed.setEnabled(false);
                jTextFieldCrmMed.setEnabled(false);
                jTextFieldTelMed.setEnabled(false);
                jFormattedTextFieldDtnMed.setEnabled(false);
                jComboBoxSexoMed.setEnabled(false);
                jButtonSalvarMed.setEnabled(false);
                jTextFieldNomeMed.setText("");
                jTextFieldCpfMed.setText("");
                jTextFieldCrmMed.setText("");
                jFormattedTextFieldDtnMed.setText("");
                jTextFieldTelMed.setText("");
                jComboBoxSexoMed.setSelectedItem("");
                jTextFieldPesqMed.setEnabled(true);
                jButtonNovoCadMed.setEnabled(true);
                preencherTabela("select * from medico order by cd_medico");
            }
        }
    }//GEN-LAST:event_jButtonSalvarMedActionPerformed

    private void jButtonPesqMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqMedActionPerformed
        medico.setPesquisa(jTextFieldPesqMed.getText());
        ModelMed modelMed = persistMed.buscaMed(medico);
        jTextFieldCodMed.setText(String.valueOf(modelMed.getCod()));
        jTextFieldNomeMed.setText(modelMed.getNome());
        jTextFieldCpfMed.setText(modelMed.getCpf());
        jTextFieldCrmMed.setText(String.valueOf(modelMed.getCrm()));
        jFormattedTextFieldDtnMed.setText(modelMed.getDtn());
        jComboBoxSexoMed.setSelectedItem(modelMed.getSexo());
        jTextFieldTelMed.setText(modelMed.getTelefone());
        jButtonEditMed.setEnabled(true);
        jButtonDelMed.setEnabled(true);
        preencherTabela("select * from medico where nm_medico like '%" + medico.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesqMedActionPerformed

    private void jButtonEditMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMedActionPerformed
        event = "EDITAR";
        jTextFieldNomeMed.setEnabled(true);
        jTextFieldCrmMed.setEnabled(true);
        jTextFieldTelMed.setEnabled(true);
        jComboBoxSexoMed.setEnabled(true);
        jFormattedTextFieldDtnMed.setEnabled(true);
        jTextFieldCpfMed.setEnabled(true);
        jButtonSalvarMed.setEnabled(true);
        jButtonCancelMed.setEnabled(true);
        jButtonNovoCadMed.setEnabled(false);
        jButtonEditMed.setEnabled(false);
        jButtonDelMed.setEnabled(false);
        preencherTabela("select * from medico order by cd_medico");

    }//GEN-LAST:event_jButtonEditMedActionPerformed

    private void jButtonCancelMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelMedActionPerformed
        event = "CANCELAR";
        jButtonNovoCadMed.setEnabled(true);
        jTextFieldNomeMed.setEnabled(!true);
        jTextFieldCrmMed.setEnabled(!true);
        jTextFieldTelMed.setEnabled(!true);
        jComboBoxSexoMed.setEnabled(!true);
        jFormattedTextFieldDtnMed.setEnabled(!true);
        jTextFieldCpfMed.setEnabled(!true);
        jButtonEditMed.setEnabled(false);
        jButtonDelMed.setEnabled(false);
        jTextFieldNomeMed.setText("");
        jTextFieldCpfMed.setText("");
        jTextFieldCrmMed.setText("");
        jFormattedTextFieldDtnMed.setText("");
        jTextFieldTelMed.setText("");
        jComboBoxSexoMed.setSelectedItem("");
        jButtonSalvarMed.setEnabled(false);

    }//GEN-LAST:event_jButtonCancelMedActionPerformed

    private void jTextFieldNomeMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeMedActionPerformed

    private void jTextFieldTelMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelMedActionPerformed

    private void jButtonDelMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelMedActionPerformed
        int confirmar = 0;
        confirmar = JOptionPane.showConfirmDialog(this, "Deseja realmente Deletar o cadastro?");
        if (confirmar == JOptionPane.YES_OPTION) {
            medico.setCod(Integer.parseInt(jTextFieldCodMed.getText()));
            persistMed.deletarMed(medico);
            jTextFieldNomeMed.setText("");
            jTextFieldCpfMed.setText("");
            jTextFieldCrmMed.setText("");
            jFormattedTextFieldDtnMed.setText("");
            jTextFieldTelMed.setText("");
            jComboBoxSexoMed.setSelectedItem("");
            jTextFieldNomeMed.setEnabled(false);
            jTextFieldCpfMed.setEnabled(false);
            jTextFieldCrmMed.setEnabled(false);
            jTextFieldTelMed.setEnabled(false);
            jFormattedTextFieldDtnMed.setEnabled(false);
            jComboBoxSexoMed.setEnabled(false);
            jButtonSalvarMed.setEnabled(false);
            jButtonDelMed.setEnabled(false);
            jButtonEditMed.setEnabled(false);
            jButtonSairMed.setEnabled(true);
            jButtonNovoCadMed.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Cadastro excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada!");
        }
        preencherTabela("select * from medico order by cd_medico");
    }//GEN-LAST:event_jButtonDelMedActionPerformed

    private void jTableMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicosMouseClicked
        String nome_med = "" + jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 1);
        conn.conexao();
        conn.executaPesquisa("select *from medico where nm_medico='" + nome_med + "'");
        try {
            conn.rs.first();
            jTextFieldCodMed.setText(String.valueOf(conn.rs.getInt("cd_medico")));
            jTextFieldNomeMed.setText(conn.rs.getString("nm_medico"));
            jTextFieldCpfMed.setText(conn.rs.getString("cpf_med"));
            jTextFieldCrmMed.setText(String.valueOf(conn.rs.getInt("crm_medico")));
            jComboBoxSexoMed.setSelectedItem(conn.rs.getString("sexo_medico"));
            jTextFieldTelMed.setText(conn.rs.getString("tel_medico"));
            jFormattedTextFieldDtnMed.setText(conn.rs.getString("dtn_medico"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar dados" + ex);
        }
        conn.desconectar();
        jButtonNovoCadMed.setEnabled(false);
        jButtonEditMed.setEnabled(true);
        jButtonDelMed.setEnabled(true);
        jButtonCancelMed.setEnabled(true);
        jButtonSalvarMed.setEnabled(false);

    }//GEN-LAST:event_jTableMedicosMouseClicked

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Nome", "CPF", "CRM", "Sexo", "Telefone", "Data de Nascimento"};
        conn.conexao();
        conn.executaPesquisa(sql);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getInt("cd_medico"),
                    conn.rs.getString("nm_medico"), conn.rs.getString("cpf_med"),
                    conn.rs.getInt("crm_medico"), conn.rs.getString("sexo_medico"),
                    conn.rs.getString("tel_medico"), conn.rs.getString("dtn_medico")
                });
            } while (conn.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher ArrayList" + ex);
        }
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTableMedicos.setModel(modelo);
        jTableMedicos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableMedicos.getColumnModel().getColumn(0).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTableMedicos.getColumnModel().getColumn(1).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableMedicos.getColumnModel().getColumn(2).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableMedicos.getColumnModel().getColumn(3).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableMedicos.getColumnModel().getColumn(4).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableMedicos.getColumnModel().getColumn(5).setResizable(false);
        jTableMedicos.getColumnModel().getColumn(6).setPreferredWidth(125);
        jTableMedicos.getColumnModel().getColumn(6).setResizable(false);
        jTableMedicos.setAutoResizeMode(jTableMedicos.AUTO_RESIZE_OFF);
        jTableMedicos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conn.desconectar();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelMed;
    private javax.swing.JButton jButtonDelMed;
    private javax.swing.JButton jButtonEditMed;
    private javax.swing.JButton jButtonNovoCadMed;
    private javax.swing.JButton jButtonPesqMed;
    private javax.swing.JButton jButtonSairMed;
    private javax.swing.JButton jButtonSalvarMed;
    private javax.swing.JComboBox jComboBoxSexoMed;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtnMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextFieldCodMed;
    private javax.swing.JTextField jTextFieldCpfMed;
    private javax.swing.JTextField jTextFieldCrmMed;
    private javax.swing.JTextField jTextFieldNomeMed;
    private javax.swing.JTextField jTextFieldPesqMed;
    private javax.swing.JTextField jTextFieldTelMed;
    // End of variables declaration//GEN-END:variables
}
