package trabalhofinal.view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import trabalhofinal.model.ModelPessoa;
import trabalhofinal.model.ModelTabela;
import trabalhofinal.persistence.ConexaoBD;
import trabalhofinal.persistence.PessoaDAO;

/**
 *
 * @author 320079589
 */
public class TelaPaciente extends javax.swing.JFrame {

    ConexaoBD conn = new ConexaoBD();
    ModelPessoa paciente = new ModelPessoa();
    PessoaDAO persistPes = new PessoaDAO();
    String event = "";

    public TelaPaciente() {
        initComponents();
        
        preencherTabela("select * from pessoa order by cd_pessoa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNomePac = new javax.swing.JTextField();
        jLabelDtnPac = new javax.swing.JLabel();
        jFormattedTextFieldDtnPac = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCPFpac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSexoPac = new javax.swing.JComboBox();
        jButtonAddPac = new javax.swing.JButton();
        jButtonEditarPac = new javax.swing.JButton();
        jButtonDeletarPac = new javax.swing.JButton();
        jButtonSairPac = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEstadoCPac = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jButtonPesqPac = new javax.swing.JButton();
        jButtonSalvarPac = new javax.swing.JButton();
        jTextFieldPesquisaPac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelPac = new javax.swing.JTextField();
        jButtonCancelPac = new javax.swing.JButton();
        jTextFieldCodPac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNome.setText("Nome:");

        jTextFieldNomePac.setEnabled(false);

        jLabelDtnPac.setText("Data Nasc.:");

        jFormattedTextFieldDtnPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldDtnPac.setEnabled(false);

        jLabel2.setText("CPF:");

        jTextFieldCPFpac.setEnabled(false);

        jLabel1.setText("Sexo:");

        jComboBoxSexoPac.setEditable(true);
        jComboBoxSexoPac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Masculino", "Feminino" }));
        jComboBoxSexoPac.setToolTipText("");
        jComboBoxSexoPac.setEnabled(false);
        jComboBoxSexoPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoPacActionPerformed(evt);
            }
        });

        jButtonAddPac.setText("Novo");
        jButtonAddPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPacActionPerformed(evt);
            }
        });

        jButtonEditarPac.setText("Editar");
        jButtonEditarPac.setEnabled(false);
        jButtonEditarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPacActionPerformed(evt);
            }
        });

        jButtonDeletarPac.setText("Deletar");
        jButtonDeletarPac.setEnabled(false);
        jButtonDeletarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarPacActionPerformed(evt);
            }
        });

        jButtonSairPac.setText("Sair");
        jButtonSairPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairPacActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado Civil");

        jComboBoxEstadoCPac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Amasiado(a)" }));
        jComboBoxEstadoCPac.setEnabled(false);

        jLabel4.setText("Telefone: ");

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jButtonPesqPac.setText("Pesquisar");
        jButtonPesqPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqPacActionPerformed(evt);
            }
        });

        jButtonSalvarPac.setText("Salvar");
        jButtonSalvarPac.setEnabled(false);
        jButtonSalvarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarPacActionPerformed(evt);
            }
        });

        jTextFieldPesquisaPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaPacActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CADASTRO DE PACIENTE");

        jTextFieldTelPac.setEnabled(false);
        jTextFieldTelPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelPacActionPerformed(evt);
            }
        });

        jButtonCancelPac.setText("Cancelar");
        jButtonCancelPac.setEnabled(false);
        jButtonCancelPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelPacActionPerformed(evt);
            }
        });

        jTextFieldCodPac.setEnabled(false);

        jLabel6.setText("Código:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCPFpac, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jComboBoxEstadoCPac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDtnPac, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDtnPac, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonAddPac, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeletarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSairPac, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jButtonPesqPac))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jTextFieldPesquisaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCPFpac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstadoCPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDtnPac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDtnPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jTextFieldPesquisaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPesqPac)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddPac)
                    .addComponent(jButtonEditarPac)
                    .addComponent(jButtonDeletarPac)
                    .addComponent(jButtonSairPac)
                    .addComponent(jButtonSalvarPac)
                    .addComponent(jButtonCancelPac))
                .addGap(38, 38, 38))
        );

        setSize(new java.awt.Dimension(756, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSexoPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoPacActionPerformed

    }//GEN-LAST:event_jComboBoxSexoPacActionPerformed

    private void jButtonSairPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairPacActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairPacActionPerformed

    private void jTextFieldPesquisaPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaPacActionPerformed

    private void jButtonAddPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPacActionPerformed
        event = "NOVO";
        jButtonAddPac.setEnabled(false);
        jButtonSalvarPac.setEnabled(true);
        jTextFieldNomePac.setEnabled(true);
        jTextFieldCPFpac.setEnabled(true);
        jTextFieldTelPac.setEnabled(true);
        jComboBoxSexoPac.setEnabled(true);
        jComboBoxEstadoCPac.setEnabled(true);
        jFormattedTextFieldDtnPac.setEnabled(true);
        jButtonPesqPac.setEnabled(false);
        jTextFieldPesquisaPac.setEnabled(false);
        jButtonCancelPac.setEnabled(true);
        jButtonAddPac.setEnabled(false);
    }//GEN-LAST:event_jButtonAddPacActionPerformed

    private void jButtonSalvarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarPacActionPerformed
        if (jTextFieldNomePac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o NOME para continuar!");
            jTextFieldNomePac.requestFocus();
        } else if (jTextFieldCPFpac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha CPF para continuar!");
            jTextFieldCPFpac.requestFocus();
        } else if (jComboBoxEstadoCPac.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha o Estado Civil para continuar!");
            jComboBoxEstadoCPac.requestFocus();
        } else if (jComboBoxSexoPac.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha o SEXO para continuar!");
            jComboBoxSexoPac.requestFocus();
        } else if (jTextFieldTelPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o Telefone para continuar!");
            jTextFieldTelPac.requestFocus();
        } else if (jFormattedTextFieldDtnPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha a Data de Nasc. para continuar!");
            jFormattedTextFieldDtnPac.requestFocus();
        } else {
            if ("NOVO".equals(event)) {
                paciente.setNome(jTextFieldNomePac.getText());
                paciente.setCpf(jTextFieldCPFpac.getText());
                paciente.setEstCivil((String) (jComboBoxEstadoCPac.getSelectedItem()));
                paciente.setSexo((String) jComboBoxSexoPac.getSelectedItem());
                paciente.setTelefone(jTextFieldTelPac.getText());
                paciente.setDtn(jFormattedTextFieldDtnPac.getText());
                persistPes.salvar(paciente);
                jTextFieldNomePac.setText("");
                jTextFieldCPFpac.setText("");
                jComboBoxEstadoCPac.setSelectedItem("");
                jFormattedTextFieldDtnPac.setText("");
                jTextFieldTelPac.setText("");
                jComboBoxSexoPac.setSelectedItem("");
                jTextFieldNomePac.setEnabled(false);
                jTextFieldCPFpac.setEnabled(false);
                jComboBoxEstadoCPac.setEnabled(false);
                jTextFieldTelPac.setEnabled(false);
                jFormattedTextFieldDtnPac.setEnabled(false);
                jComboBoxSexoPac.setEnabled(false);
                jButtonSalvarPac.setEnabled(false);
                jButtonPesqPac.setEnabled(true);
                jTextFieldPesquisaPac.setEnabled(true);
                preencherTabela("select * from pessoa order by cd_pessoa");

            } else {
                paciente.setCod(Integer.parseInt(jTextFieldCodPac.getText()));
                paciente.setNome(jTextFieldNomePac.getText());
                paciente.setCpf(jTextFieldCPFpac.getText());
                paciente.setEstCivil((String)jComboBoxEstadoCPac.getSelectedItem());
                paciente.setSexo((String) jComboBoxSexoPac.getSelectedItem());
                paciente.setTelefone(jTextFieldTelPac.getText());
                paciente.setDtn(jFormattedTextFieldDtnPac.getText());
                persistPes.editar(paciente);
                jTextFieldNomePac.setEnabled(false);
                jTextFieldCPFpac.setEnabled(false);
                jComboBoxEstadoCPac.setEnabled(false);
                jTextFieldTelPac.setEnabled(false);
                jFormattedTextFieldDtnPac.setEnabled(false);
                jComboBoxSexoPac.setEnabled(false);
                jButtonSalvarPac.setEnabled(false);
                jTextFieldNomePac.setText("");
                jTextFieldCPFpac.setText("");
                jComboBoxEstadoCPac.setSelectedItem("");
                jFormattedTextFieldDtnPac.setText("");
                jTextFieldTelPac.setText("");
                jComboBoxSexoPac.setSelectedItem("");
                jTextFieldPesquisaPac.setEnabled(true);
                jButtonAddPac.setEnabled(true);
                preencherTabela("select * from pessoa order by cd_pessoa");
            }
        }
    }//GEN-LAST:event_jButtonSalvarPacActionPerformed

    private void jButtonPesqPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqPacActionPerformed
        paciente.setPesquisa(jTextFieldPesquisaPac.getText());
        ModelPessoa modelPes = persistPes.buscaPes(paciente);
        jTextFieldCodPac.setText(String.valueOf(modelPes.getCod()));
        jTextFieldNomePac.setText(modelPes.getNome());
        jTextFieldCPFpac.setText(modelPes.getCpf());
        jComboBoxSexoPac.setSelectedItem(modelPes.getSexo());
        jComboBoxEstadoCPac.setSelectedItem(modelPes.getEstCivil());
        jTextFieldTelPac.setText(modelPes.getTelefone());
        jFormattedTextFieldDtnPac.setText(modelPes.getDtn());
        //jButtonEdit.setEnabled(true);
        jButtonDeletarPac.setEnabled(true);
    }//GEN-LAST:event_jButtonPesqPacActionPerformed

    private void jTextFieldTelPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelPacActionPerformed

    private void jButtonEditarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPacActionPerformed
        event = "EDITAR";
        jTextFieldNomePac.setEnabled(true);
        jTextFieldTelPac.setEnabled(true);
        jComboBoxEstadoCPac.setEnabled(true);
        jComboBoxSexoPac.setEnabled(true);
        jFormattedTextFieldDtnPac.setEnabled(true);
        jTextFieldCPFpac.setEnabled(true);
        jButtonAddPac.setEnabled(true);
        jButtonCancelPac.setEnabled(true);
        jButtonSalvarPac.setEnabled(true);
        jButtonAddPac.setEnabled(false);
        jButtonEditarPac.setEnabled(false);
        jButtonDeletarPac.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarPacActionPerformed

    private void jButtonDeletarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarPacActionPerformed
        int confirmar = 0;
        confirmar = JOptionPane.showConfirmDialog(this, "Deseja realmente Deletar o cadastro?");
        if (confirmar == JOptionPane.YES_OPTION) {
            paciente.setCod(Integer.parseInt(jTextFieldCodPac.getText()));
            persistPes.deletarPac(paciente);
            jTextFieldNomePac.setText("");
            jTextFieldCPFpac.setText("");
            jComboBoxEstadoCPac.setSelectedItem("");
            jFormattedTextFieldDtnPac.setText("");
            jTextFieldTelPac.setText("");
            jComboBoxSexoPac.setSelectedItem("");
            jTextFieldNomePac.setEnabled(false);
            jTextFieldCPFpac.setEnabled(false);
            jComboBoxEstadoCPac.setEnabled(false);
            jTextFieldTelPac.setEnabled(false);
            jFormattedTextFieldDtnPac.setEnabled(false);
            jComboBoxSexoPac.setEnabled(false);
            jButtonAddPac.setEnabled(false);
            jButtonDeletarPac.setEnabled(false);
            jButtonEditarPac.setEnabled(false);
            jButtonSairPac.setEnabled(true);
            jButtonAddPac.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Cadastro excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada!");
        }
        preencherTabela("select * from pessoa order by cd_pessoa");

    }//GEN-LAST:event_jButtonDeletarPacActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
        String nome_pes = "" + jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(), 1);
        conn.conexao();
        conn.executaPesquisa("select *from pessoa where nm_pessoa='" + nome_pes + "'");
        try {
            conn.rs.first();
            jTextFieldCodPac.setText(String.valueOf(conn.rs.getInt("cd_pessoa")));
            jTextFieldNomePac.setText(conn.rs.getString("nm_pessoa"));
            jTextFieldCPFpac.setText(conn.rs.getString("cpf_pessoa"));
            jComboBoxEstadoCPac.setSelectedItem((conn.rs.getString("est_civil_pessoa")));
            jComboBoxSexoPac.setSelectedItem(conn.rs.getString("sexo_pessoa"));
            jTextFieldTelPac.setText(conn.rs.getString("telefone_pessoa"));
            jFormattedTextFieldDtnPac.setText(conn.rs.getString("dtn_pessoa"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar dados" + ex);
        }
        conn.desconectar();
        jButtonAddPac.setEnabled(false);
        jButtonEditarPac.setEnabled(true);
        jButtonDeletarPac.setEnabled(true);
        jButtonCancelPac.setEnabled(true);
        jButtonSalvarPac.setEnabled(false);

    }//GEN-LAST:event_jTablePacienteMouseClicked

    private void jButtonCancelPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelPacActionPerformed
        event = "CANCELAR";
        jButtonAddPac.setEnabled(true);
        jTextFieldNomePac.setEnabled(!true);
        jComboBoxEstadoCPac.setEnabled(!true);
        jTextFieldTelPac.setEnabled(!true);
        jComboBoxSexoPac.setEnabled(!true);
        jFormattedTextFieldDtnPac.setEnabled(!true);
        jTextFieldCPFpac.setEnabled(!true);
        jButtonEditarPac.setEnabled(false);
        jButtonDeletarPac.setEnabled(false);
        jTextFieldNomePac.setText("");
        jTextFieldCPFpac.setText("");
        jComboBoxEstadoCPac.setSelectedItem("");
        jFormattedTextFieldDtnPac.setText("");
        jTextFieldTelPac.setText("");
        jComboBoxSexoPac.setSelectedItem("");
        jButtonSalvarPac.setEnabled(false);

    }//GEN-LAST:event_jButtonCancelPacActionPerformed

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Nome", "CPF", "Estado Civil", "Sexo", "Telefone", "Data de Nascimento"};
        conn.conexao();
        conn.executaPesquisa(sql);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getInt("cd_pessoa"),
                    conn.rs.getString("nm_pessoa"), conn.rs.getString("cpf_pessoa"),
                    conn.rs.getString("est_civil_pessoa"), conn.rs.getString("sexo_pessoa"),
                    conn.rs.getString("telefone_pessoa"), conn.rs.getString("dtn_pessoa")
                });
            } while (conn.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lista Vazia");
        }
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTablePaciente.setModel(modelo);
        jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTablePaciente.getColumnModel().getColumn(0).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTablePaciente.getColumnModel().getColumn(1).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablePaciente.getColumnModel().getColumn(2).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTablePaciente.getColumnModel().getColumn(3).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTablePaciente.getColumnModel().getColumn(4).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTablePaciente.getColumnModel().getColumn(5).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(6).setPreferredWidth(125);
        jTablePaciente.getColumnModel().getColumn(6).setResizable(false);
        jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF);
        jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conn.desconectar();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPac;
    private javax.swing.JButton jButtonCancelPac;
    private javax.swing.JButton jButtonDeletarPac;
    private javax.swing.JButton jButtonEditarPac;
    private javax.swing.JButton jButtonPesqPac;
    private javax.swing.JButton jButtonSairPac;
    private javax.swing.JButton jButtonSalvarPac;
    private javax.swing.JComboBox jComboBoxEstadoCPac;
    private javax.swing.JComboBox jComboBoxSexoPac;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtnPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDtnPac;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldCPFpac;
    private javax.swing.JTextField jTextFieldCodPac;
    private javax.swing.JTextField jTextFieldNomePac;
    private javax.swing.JTextField jTextFieldPesquisaPac;
    private javax.swing.JTextField jTextFieldTelPac;
    // End of variables declaration//GEN-END:variables
}
